### ISSUE TITLE
I am having trouble running this

### ISSUE THREAD

**Issue by WaffleBits** [Geofed/Rainbow-Rank-for-Discord#1]
First I reverted back to discord.js v8 from v9 because v9 does't work with old bots (or the .js bots i've seen so far). But now I get this error `Error: Cannot find module './options.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/topkek/snbot/rainbowrank.js:4:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
`

**Comment by FatRagdoll** [comment]
Yea I'm getting the same error, it's probably because the rainbowrank.js requires a options.json file, but it doesn't exist in the Zip file what soo ever.

**Comment by IMINCANE711** [comment]
how do i use this
